### ISSUE TITLE
Katib controller goes into CrashLoopBackoff when no goal is specified

### ISSUE THREAD

**Issue by borremosch** [kubeflow/katib#1060]
/kind bug

**What steps did you take and what happened:**
I created an experiment without a `goal`. The spec validated fine, but consequently the Katib controller entered a faulty state from which recovery seems impossible. I had to delete and re-install Katib entirely into my development cluster. Logs from the controller are as follows:

```{"level":"info","ts":1582106357.593974,"logger":"trial-controller","msg":"Trial  controller created"}
{"level":"info","ts":1582106357.5939763,"logger":"entrypoint","msg":"Setting up webhooks"}
{"level":"info","ts":1582106357.5940497,"logger":"entrypoint","msg":"Starting the Cmd."}
{"level":"info","ts":1582106357.694709,"logger":"kubebuilder.webhook","msg":"installing webhook configuration in cluster"}
{"level":"info","ts":1582106357.694735,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"suggestion-controller"}
{"level":"info","ts":1582106357.6947956,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"trial-controller"}
{"level":"info","ts":1582106357.6948807,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"experiment-controller"}
{"level":"info","ts":1582106357.794992,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"trial-controller","worker count":1}
{"level":"info","ts":1582106357.794992,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"suggestion-controller","worker count":1}
{"level":"info","ts":1582106357.7957547,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"experiment-controller","worker count":1}
{"level":"info","ts":1582106357.7958603,"logger":"experiment-controller","msg":"Statistics","Experiment":"project-github-test-ae92s/experiment-run-workflow-fh6kw","requiredActiveCount":5,"parallelCount":5,"activeCount":0,"completedCount":0}
{"level":"info","ts":1582106357.7958694,"logger":"experiment-controller","msg":"CreateTrials","Experiment":"project-github-test-ae92s/experiment-run-workflow-fh6kw","addCount":5}
{"level":"info","ts":1582106357.7959068,"logger":"experiment-controller","msg":"GetOrCreateSuggestion","Experiment":"project-github-test-ae92s/experiment-run-workflow-fh6kw","Instance name":"experiment-run-workflow-fh6kw","suggestionRequestsCount":5}
E0219 09:59:17.895958       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:679
/usr/local/go/src/runtime/panic.go:199
/usr/local/go/src/runtime/signal_unix.go:394
/go/src/github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go:158
/go/src/github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go:119
/go/src/github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestion_controller.go:212
/go/src/github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestion_controller.go:148
/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1357
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12111cf]

goroutine 220 [running]:
github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x14f3f20, 0x254b620)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestionclient.(*General).ConvertExperiment(0x2584430, 0xc000c66280, 0xdf8475800)
	/go/src/github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go:158 +0x1df
github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestionclient.(*General).ValidateAlgorithmSettings(0x2584430, 0xc00016bd40, 0xc000c66280, 0x0, 0x0)
	/go/src/github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go:119 +0x303
github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion.(*ReconcileSuggestion).ReconcileSuggestion(0xc0007474a0, 0xc00016bd40, 0xc000048028, 0xc0008eb9a0)
	/go/src/github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestion_controller.go:212 +0x5de
github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion.(*ReconcileSuggestion).Reconcile(0xc0007474a0, 0xc0008eb9a0, 0x19, 0xc0008eb980, 0x1d, 0xc0002ec360, 0x0, 0x0, 0xc0002c6700)
	/go/src/github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestion_controller.go:148 +0x37e
github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000427900, 0x0)
	/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x20a
github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0002da080)
	/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0002da080, 0x3b9aca00, 0x0, 0x1, 0xc0006b4120)
	/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0002da080, 0x3b9aca00, 0xc0006b4120)
	/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x32e
```

**What did you expect to happen:**
I expected the experiment to run.

**Environment:**

- Kubeflow version: 0.8.0
- Minikube version: 1.6.2
- Kubernetes version: 1.12
- OS (e.g. from `/etc/os-release`): Ubuntu 19.10

**Comment by andreyvelich** [comment]
@borremosch What is your use case, when you run Experiment without the `Goal`?

**Comment by borremosch** [comment]
@andreyvelich I want to run a hyperparameter search without having to worry beforehand about what a good enough performance is

**Comment by andreyvelich** [comment]
@johnugeorge In that case, what do you think? 
Should we add functionality to run experiments without Goal? We have to make some changes in the Katib Controller for it.

**Comment by janvdvegt** [comment]
In many cases the goal is just to find the most optimal value, right? Usually, the amount of time or compute you want to spend on a problem is more relevant than some specific value, unless that value is the theoretical maximum. Alternatively, some early stopping might be relevant but I would phrase it differently then, maybe the number of trials that have not improved the maximum score fits better.

**Comment by johnugeorge** [comment]
It makes sense. We should solve this. It looks to be a simple fix as our implementation already supports it.

**Comment by andreyvelich** [comment]
Ok, I will add it.
/assign @andreyvelich
