### ISSUE TITLE
katib manager is going to CrashLoopBackOff due to katib db is not up with MYSQL_ROOT_PASSWORD  for root user

### ISSUE THREAD

**Issue by hemantha-kumara** [kubeflow/katib#1115]
/kind bug

**What steps did you take and what happened:**
Kubeflow 0.7.1 installed on the on-prem cluster(issue might come even in 1.0.x)

**katib manager is going to CrashLoopBackOff state**

```
Warning Unhealthy 14m (x5441 over 3d15h) kubelet, corsica-worker-05 Readiness probe failed: timeout: failed to connect service ":6789" within 1s
Warning BackOff 4m48s (x19677 over 3d15h) kubelet, corsica-worker-05 Back-off restarting failed container

```
**Katib db is not going ready state**
`katib-db-677b68774f-mvbxn 0/1 Running 1 3d15h`

Katib manager logs

```
E0317 07:48:08.671150 1 mysql.go:57] Ping to Katib db failed: dial tcp 10.254.131.230:3306: i/o timeout
E0317 07:48:13.673131 1 mysql.go:57] Ping to Katib db failed: dial tcp 10.254.131.230:3306: i/o timeout
E0317 07:48:19.148986 1 mysql.go:57] Ping to Katib db failed: dial tcp 10.254.131.230:3306: i/o timeout
E0317 07:48:24.149722 1 mysql.go:57] Ping to Katib db failed: dial tcp 10.254.131.230:3306: i/o timeout
E0317 07:48:29.150049 1 mysql.go:57] Ping to Katib db failed: dial tcp 10.254.131.230:3306: i/o timeout
E0317 07:48:34.150400 1 mysql.go:57] Ping to Katib db failed: dial tcp 10.254.131.230:3306: i/o timeout
E0317 07:48:39.150680 1 mysql.go:57] Ping to Katib db failed: dial tcp 10.254.131.230:3306: i/o timeout
E0317 07:48:44.151060 1 mysql.go:57] Ping to Katib db failed: dial tcp 10.254.131.230:3306: i/o timeout
E0317 07:48:49.151455 1 mysql.go:57] Ping to Katib db failed: dial tcp 10.254.131.230:3306: i/o timeout
E0317 07:48:54.388585 1 mysql.go:57] Ping to Katib db failed: dial tcp 10.254.131.230:3306: i/o timeout
E0317 07:48:59.388868 1 mysql.go:57] Ping to Katib db failed: dial tcp 10.254.131.230:3306: i/o timeout
F0317 07:48:59.389130 1 main.go:83] Failed to open db connection: DB open failed: Timeout waiting for DB conn successfully opened.
goroutine 1 [running]:
github.com/kubeflow/katib/vendor/k8s.io/klog.stacks(0xc000170400, 0xc0001fe000, 0x89, 0xc2)
/go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:830 +0xb8
github.com/kubeflow/katib/vendor/k8s.io/klog.(*loggingT).output(0xdf1c80, 0xc000000003, 0xc00015fb90, 0xd93747, 0x7, 0x53, 0x0)
/go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:781 +0x2d0
github.com/kubeflow/katib/vendor/k8s.io/klog.(*loggingT).printf(0xdf1c80, 0x3, 0x9b4416, 0x20, 0xc000167f20, 0x1, 0x1)
/go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:678 +0x14b
github.com/kubeflow/katib/vendor/k8s.io/klog.Fatalf(...)
/go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:1209
main.main()
/go/src/github.com/kubeflow/katib/cmd/manager/v1alpha3/main.go:83 +0x165
```
when we tried to debug an issue , we could find out db pod is going for earlry reset due to this, root user password is not getting updated, hence all this issue.
`katib-db-677b68774f-mvbxn 0/1 Running 1 3d15h`

More information on this issue can find in https://github.com/docker-library/mysql/issues/653 

**What did you expect to happen:**
Katib manager and DB should be up and running.

**Anything else you would like to add:**
 [startupProbe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes) can be added to solve this issue.
 

**Environment:**

- Kubeflow version: `0.7.1`
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

```
- OS (e.g. from `/etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by andreyvelich** [comment]
@hemantha-kumara Katib manager fails because Katib mysql is not running properly. Can you describe your `katib-mysql` pod, please?

Adding `startupProbe` seems ok for me.  What do you think @gaocegege @johnugeorge ?
For example, with the same command as `readinessProbe`: https://github.com/kubeflow/katib/blob/master/manifests/v1alpha3/mysql-db/deployment.yaml#L46

**Comment by hemantha-kumara** [comment]
> Katib manager fails because Katib mysql is not running properly. Can you describe your `katib-mysql` pod, please?

I haven't collected describe pod logs but I see container status 0/1
`katib-db-677b68774f-mvbxn 0/1 Running 1 3d15h`

```
[root@corsica-control-01 acp-kubeflow]# kubectl get event -n kubeflow
LAST SEEN TYPE REASON OBJECT MESSAGE
68s Warning Unhealthy pod/katib-db-677b68774f-mvbxn Readiness probe failed: mysql: [Warning] Using a password on the command line interface can be insecure.
```

**Comment by andreyvelich** [comment]
Can you try to deploy katib-db again from here: https://github.com/kubeflow/katib/tree/master/manifests/v1alpha3/mysql-db.

And run `kubectl describe pod <katib db pod name> -n kubeflow`.
