### ISSUE TITLE
Katib crashed with invalid memory reference error

### ISSUE THREAD

**Issue by vpavlin** [kubeflow/katib#1242]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Deployed Katib via Kubeflow, added `darts` in to `katib-config` and submitted darts example resource

```
E0626 14:58:49.927267       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:679
/usr/local/go/src/runtime/panic.go:199
/usr/local/go/src/runtime/signal_unix.go:394
/go/src/github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go:158
/go/src/github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go:119
/go/src/github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestion_controller.go:212
/go/src/github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestion_controller.go:148
/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1357
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12111cf]

goroutine 347 [running]:
github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x14f3f20, 0x254b620)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestionclient.(*General).ConvertExperiment(0x2584430, 0xc0000e0c80, 0xdf8475800)
	/go/src/github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go:158 +0x1df
github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestionclient.(*General).ValidateAlgorithmSettings(0x2584430, 0xc00069a9c0, 0xc0000e0c80, 0x0, 0x0)
	/go/src/github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go:119 +0x303
github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion.(*ReconcileSuggestion).ReconcileSuggestion(0xc0002d6050, 0xc00069a9c0, 0xc0000ca018, 0xc0005242c0)
	/go/src/github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestion_controller.go:212 +0x5de
github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion.(*ReconcileSuggestion).Reconcile(0xc0002d6050, 0xc0005242c0, 0x8, 0xc0000cc980, 0x11, 0xc000de6a00, 0x0, 0x0, 0x0)
	/go/src/github.com/kubeflow/katib/pkg/controller.v1alpha3/suggestion/suggestion_controller.go:148 +0x37e
github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00018c320, 0xc0000ee800)
	/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x20a
github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0000800b0)
	/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0000800b0, 0x3b9aca00, 0x0, 0x1, 0xc00031e300)
	/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0000800b0, 0x3b9aca00, 0xc00031e300)
	/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x32e
```

**What did you expect to happen:**
The controller does not fail

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by gaocegege** [comment]
cc @andreyvelich

**Comment by andreyvelich** [comment]
@vpavlin Which Kubeflow version did you deploy? If you are using master branch, `katib-config` already contains `darts`: https://github.com/kubeflow/manifests/blob/master/katib/katib-controller/base/katib-configmap.yaml#L52-L54.

Also, can you show the experiment please.

**Comment by andreyvelich** [comment]
@vpavlin I close this issue, feel free to re-open if you have any other questions.
