### ISSUE TITLE
http server panic, in katib controller with even the provided sample experiments.

### ISSUE THREAD

**Issue by ScrapCodes** [kubeflow/katib#1435]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
On running the sample mnist experiment with kubeflow version 1.2.0 and katib version 0.10.1

While running the experiment, I am getting following error:
```
NFO:root:Creating Experiment: mnist in namespace: prashant
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kubeflow/katib/api/katib_client.py", line 74, in create_experiment
    exp_object)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/custom_objects_api.py", line 178, in create_namespaced_custom_object
    (data) = self.create_namespaced_custom_object_with_http_info(group, version, namespace, plural, body, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/custom_objects_api.py", line 277, in create_namespaced_custom_object_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 377, in request
    body=body)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 266, in POST
    body=body)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 17 Feb 2021 08:37:23 GMT', 'Content-Length': '479'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Internal error occurred: failed calling webhook \"mutating.experiment.katib.kubeflow.org\": Post https://katib-controller.kubeflow.svc:443/mutate-experiments?timeout=30s: EOF","reason":"InternalError","details":{"causes":[{"message":"failed calling webhook \"mutating.experiment.katib.kubeflow.org\": Post https://katib-controller.kubeflow.svc:443/mutate-experiments?timeout=30s: EOF"}]},"code":500}https://katib-controller.kubeflow.svc:443/mutate-experiments?timeout=30s: EOF"}]},"code":500}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "src/launch_experiment.py", line 115, in <module>
    output = katib_client.create_experiment(experiment, namespace=experiment_namespace)
  File "/usr/local/lib/python3.6/site-packages/kubeflow/katib/api/katib_client.py", line 78, in create_experiment
    %s\n" % e)
RuntimeError: Exception when calling CustomObjectsApi->create_namespaced_custom_object:         (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 17 Feb 2021 08:37:23 GMT', 'Content-Length': '479'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Internal error occurred: failed calling webhook \"mutating.experiment.katib.kubeflow.org\": Post https://katib-controller.kubeflow.svc:443/mutate-experiments?timeout=30s: EOF","reason":"InternalError","details":{"causes":[{"message":"failed calling webhook \"mutating.experiment.katib.kubeflow.org\": Post https://katib-controller.kubeflow.svc:443/mutate-experiments?timeout=30s: EOF"}]},"code":500}https://katib-controller.kubeflow.svc:443/mutate-experiments?timeout=30s: EOF"}]},"code":500}

```

and Following http panic in katib-controller pod
```
2021/02/17 08:37:23 http: panic serving 172.17.47.2:55394: runtime error: invalid memory address or nil pointer dereference
goroutine 678780 [running]:
net/http.(*conn).serve.func1(0xc00019c280)
	/usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x1507140, 0x2229490)
	/usr/local/go/src/runtime/panic.go:975 +0x47a
github.com/kubeflow/katib/pkg/apis/controller/experiments/v1beta1.(*Experiment).setDefaultObjective(0xc0003c6840)
	/go/src/github.com/kubeflow/katib/pkg/apis/controller/experiments/v1beta1/experiment_defaults.go:53 +0x55
github.com/kubeflow/katib/pkg/apis/controller/experiments/v1beta1.(*Experiment).SetDefault(0xc0003c6840)
	/go/src/github.com/kubeflow/katib/pkg/apis/controller/experiments/v1beta1/experiment_defaults.go:33 +0x66
github.com/kubeflow/katib/pkg/webhook/v1beta1/experiment.(*experimentDefaulter).Handle(0xc000878ca0, 0x18ce8e0, 0xc000190000, 0xc000758160, 0xffffffffffffffff, 0xc000efb8c8, 0xa3ef45, 0x1894c00)
	/go/src/github.com/kubeflow/katib/pkg/webhook/v1beta1/experiment/mutate_webhook.go:47 +0xa5
github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).handleMutating(0xc0001fd780, 0x18ce8e0, 0xc000190000, 0xc000758160, 0x3, 0xc00044d300, 0xc00044d300, 0x0)
	/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go:133 +0xd8
github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle(0xc0001fd780, 0x18ce8e0, 0xc000190000, 0xc000758160, 0x0, 0x18b2120, 0xc0007523c0, 0x18b2120)
	/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go:120 +0x1fa
github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP(0xc0001fd780, 0x18c7ea0, 0xc00164e0e0, 0xc00042df00)
	/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go:93 +0x9f5
net/http.(*ServeMux).ServeHTTP(0xc0008bc780, 0x18c7ea0, 0xc00164e0e0, 0xc00042df00)
	/usr/local/go/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc000903960, 0x18c7ea0, 0xc00164e0e0, 0xc00042df00)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc00019c280, 0x18ce8a0, 0xc00060e000)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c
```
**What did you expect to happen:**
Everything worked , or at least a proper error instead of a go panic error.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Found while working on https://github.com/kubeflow/kfp-tekton/pull/468
This issue can be reproduced easily by deploying the pipeline provided in above link.

**Environment:**
```
venv) MacBook-Pro:katib prashantsharma$ pip3 list
Package                  Version   Location
------------------------ --------- --------------------------------------------------------------------
attrs                    20.3.0
cachetools               4.2.1
certifi                  2020.12.5
cffi                     1.14.5
chardet                  4.0.0
click                    7.1.2
cloudpickle              1.6.0
Deprecated               1.2.11
docstring-parser         0.7.3
google-api-core          1.26.0
google-auth              1.26.1
google-cloud-core        1.6.0
google-cloud-storage     1.36.0
google-crc32c            1.1.2
google-resumable-media   1.2.0
googleapis-common-protos 1.52.0
idna                     2.10
iniconfig                1.1.1
jsonschema               3.2.0
kfp                      1.3.0
kfp-pipeline-spec        0.1.5
kfp-server-api           1.3.0
kfp-tekton               0.6.0     /Users/prashantsharma/Work/github.com/kubeflow/kfp-tekton/sdk/python
kubeflow-katib           0.10.1
kubernetes               11.0.0
numpy                    1.20.1
oauthlib                 3.1.0
packaging                20.9
pip                      20.1.1
pluggy                   0.13.1
protobuf                 3.14.0
py                       1.10.0
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycparser                2.20
pyparsing                2.4.7
pyrsistent               0.17.3
pytest                   6.2.2
python-dateutil          2.8.1
pytz                     2021.1
PyYAML                   5.4.1
requests                 2.25.1
requests-oauthlib        1.3.0
requests-toolbelt        0.9.1
rsa                      4.7.1
setuptools               47.1.0
six                      1.15.0
strip-hints              0.1.9
table-logger             0.3.6
tabulate                 0.8.7
toml                     0.10.2
urllib3                  1.26.3
websocket-client         0.57.0
wheel                    0.36.2
wrapt                    1.12.1
WARNING: You are using pip version 20.1.1; how
```
- Kubeflow version (`kfctl version`):kfctl v1.2.0-0-gbc038f9

- Minikube version (`minikube version`): 
- Kubernetes version: (use `kubectl version`): 1.18.15
- OS (e.g. from `/etc/os-release`): Mac OS 11.2.1

**Comment by andreyvelich** [comment]
Thank you for submitting this @ScrapCodes.
I answered here: https://github.com/kubeflow/kfp-tekton/pull/468#discussion_r578622422
