### ISSUE TITLE
Trials are failing to report experiment results

### ISSUE THREAD

**Issue by cc-gb2** [kubeflow/katib#1537]
/kind bug

**What steps did you take and what happened:**
I've tried running the basic example from here: `https://github.com/kubeflow/katib/blob/master/examples/v1beta1/random-example.yaml` with some very minor modifications (`resumePolicy: Never` and to `retain: true`). However the pods are failing at the end of the job due to metric collection and reporting logs. Specifically this error:
```
F0520 15:28:07.087795      27 main.go:395] Failed to Report logs: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.100.19.82:6789: connect: connection refused"
goroutine 1 [running]:
```

The `katib-db-manager` and `katib-mysql` have been stuck in a CrashLoopBackOff, so I investigated their descriptions and logs: 

For katib-db-manager description: 

```
Name:         katib-mysql-858f68f588-cplgw
Namespace:    kubeflow
Priority:     0
Node:         ip-192-168-91-231.us-east-2.compute.internal/192.168.91.231
Start Time:   Mon, 17 May 2021 04:34:40 +0100
Labels:       app=katib
              app.kubernetes.io/component=katib
              app.kubernetes.io/name=katib-controller
              component=mysql
              pod-template-hash=858f68f588
Annotations:  kubernetes.io/psp: eks.privileged
              sidecar.istio.io/inject: false
Status:       Running
IP:           192.168.75.78
IPs:
  IP:           192.168.75.78
Controlled By:  ReplicaSet/katib-mysql-858f68f588
Containers:
  katib-mysql:
    Container ID:  docker://00563af523138393cd015b0efa649a2206d206b7d7f76a4586d1ad674b35b8e8
    Image:         mysql:8
    Image ID:      docker-pullable://mysql@sha256:00b627abbd6e91d5d0e4be786869930497b9759bf40db3f15408bb894daf5263
    Port:          3306/TCP
    Host Port:     0/TCP
    Args:
      --datadir
      /var/lib/mysql/datadir
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 20 May 2021 16:42:23 +0100
      Finished:     Thu, 20 May 2021 16:42:31 +0100
    Ready:          False
    Restart Count:  964
    Liveness:       exec [/bin/bash -c mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}] delay=30s timeout=5s period=10s #success=1 #failure=3
    Readiness:      exec [/bin/bash -c mysql -D ${MYSQL_DATABASE} -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'] delay=5s timeout=1s period=10s #suc
cess=1 #failure=3
    Environment:
      MYSQL_ROOT_PASSWORD:         <set to the key 'MYSQL_ROOT_PASSWORD' in secret 'katib-mysql-secrets'>  Optional: false
      MYSQL_ALLOW_EMPTY_PASSWORD:  true
      MYSQL_DATABASE:              katib
    Mounts:
      /var/lib/mysql from katib-mysql (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-c57st (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  katib-mysql:
    ReadOnly:   false
  default-token-c57st:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-c57st
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  Warning  Unhealthy  20m (x197 over 3d11h)  kubelet  Readiness probe failed: mysql: [Warning] Using a password on the command line interface can be
insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
  Normal   Pulled   15m (x963 over 3d11h)    kubelet  Container image "mysql:8" already present on machine
  Warning  BackOff  49s (x23177 over 3d11h)  kubelet  Back-off restarting failed container
```

The logs just repeat the no connection:
`E0520 15:34:57.821899       1 mysql.go:62] Ping to Katib db failed: dial tcp 10.100.254.212:3306: connect: connection refused
`

and the logs of the mysql pod:
```
2021-05-20 15:47:46+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.23-1debian10 started.
2021-05-20 15:47:46+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2021-05-20 15:47:47+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.23-1debian10 started.
2021-05-20T15:47:47.857518Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.23) starting as process 1
2021-05-20T15:47:48.321991Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2021-05-20T15:47:49.448118Z 1 [ERROR] [MY-013171] [InnoDB] Cannot boot server version 80023 on data directory built by version 80025. Downgrade is not supported
mysqld: Can't open file: 'mysql.ibd' (errno: 0 - )
2021-05-20T15:47:54.442640Z 1 [ERROR] [MY-010334] [Server] Failed to initialize DD Storage Engine
2021-05-20T15:47:54.443582Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
2021-05-20T15:47:54.444324Z 0 [ERROR] [MY-010119] [Server] Aborting
2021-05-20T15:47:54.475497Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.23)  MySQL Community Server - GPL.
```

How do I fix this mysql error?

**Comment by cc-gb2** [comment]
This still doesn't work, and I've double checked my code. This seems to completely invalidate the `metricsFormat`  functionality as working at all.

**Comment by andreyvelich** [comment]
Thank you for creating this @cc-gb2.
It seems that `mysql` pod is not running properly. It fails with this error:
```
Cannot boot server version 80023 on data directory built by version 80025. Downgrade is not supported
mysqld: Can't open file: 'mysql.ibd' (errno: 0 - )
```
Try to change `imagePullPolicy: Always` in the `katib-mysql` deployment and install it again.

**Comment by pablofiumara** [comment]
@cc-gb2 @andreyvelich I tried changing imagePullPolicy and installing again it but I am getting the same error `(mysqld: Can't open file: 'mysql.ibd' (errno: 0 - )`. What else can I try?
