### ISSUE TITLE
Server error when running HP jobs

### ISSUE THREAD

**Issue by VoVAllen** [kubeflow/katib#1563]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Tried the official example of pytorch katib finetuning job. And got the error log from katib-controller as below. The pods are labeled as completed through kubectl, but said running in the katib ui

```
2021/06/25 07:44:38 http: panic serving 172.31.20.244:42680: runtime error: invalid memory address or nil pointer dereference
goroutine 2081 [running]:
net/http.(*conn).serve.func1(0xc000cb40a0)
        /usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x1507140, 0x2229490)
        /usr/local/go/src/runtime/panic.go:975 +0x47a
github.com/kubeflow/katib/pkg/webhook/v1beta1/pod.(*sidecarInjector).MutationRequired(0xc000e70240, 0xc000e01180, 0xc001e9e170, 0x8, 0x0, 0x0, 0x21c402a)
        /go/src/github.com/kubeflow/katib/pkg/webhook/v1beta1/pod/inject_webhook.go:137 +0x161
github.com/kubeflow/katib/pkg/webhook/v1beta1/pod.(*sidecarInjector).Handle(0xc000e70240, 0x18ce8e0, 0xc000048030, 0xc0005cef20, 0xffffffffffffffff, 0xc000cf78c8, 0xa3ef45, 0x1894c00)
        /go/src/github.com/kubeflow/katib/pkg/webhook/v1beta1/pod/inject_webhook.go:71 +0x1bd
github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).handleMutating(0xc00099af80, 0x18ce8e0, 0xc000048030, 0xc0005cef20, 0x3, 0xc00013a040, 0xc00013a040, 0x0)
        /go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go:133 +0xd8
github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle(0xc00099af80, 0x18ce8e0, 0xc000048030, 0xc0005cef20, 0x0, 0x18b2120, 0xc001fde5a0, 0x18b2120)
        /go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go:120 +0x1fa
github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP(0xc00099af80, 0x18c7ea0, 0xc001f26000, 0xc0009d8000)
        /go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go:93 +0x9f5
net/http.(*ServeMux).ServeHTTP(0xc0004e1ac0, 0x18c7ea0, 0xc001f26000, 0xc0009d8000)
        /usr/local/go/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc0010ca2a0, 0x18c7ea0, 0xc001f26000, 0xc0009d8000)
        /usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc000cb40a0, 0x18ce8a0, 0xc001f72040)
        /usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2969 +0x36c
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version (`kfctl version`):
- Minikube version (`minikube version`):
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by VoVAllen** [comment]
Fixed by not running in the kubeflow namespace. Should have a more friendly error message
