### ISSUE TITLE
Katib model-frontend Error

### ISSUE THREAD

**Issue by xieydd** [kubeflow/katib#168]
These is no err log when i deployment katib, but whey i try the [demo](https://github.com/kubeflow/katib/blob/master/examples/MinikubeDemo.md) ,When i curl ip:3000,here is my log

```
<h1>Not Found</h1>
<h2>404</h2>
<pre>Error: Not Found
    at /modeldb/frontend/app.js:33:13
    at Layer.handle [as handle_request] (/modeldb/frontend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/modeldb/frontend/node_modules/express/lib/router/index.js:312:13)
    at /modeldb/frontend/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/modeldb/frontend/node_modules/express/lib/router/index.js:330:12)
    at next (/modeldb/frontend/node_modules/express/lib/router/index.js:271:10)
    at cookieParser (/modeldb/frontend/node_modules/cookie-parser/index.js:56:14)
    at Layer.handle [as handle_request] (/modeldb/frontend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/modeldb/frontend/node_modules/express/lib/router/index.js:312:13)
    at /modeldb/frontend/node_modules/express/lib/router/index.js:280:7</pre>
```

**Comment by xieydd** [comment]
@YujiOshima Can you help me?

**Comment by YujiOshima** [comment]
@xieydd Hmm, do you have any problems on model-db-backend?
If not, please try to access `http://127.0.0.1:3000/projects`

**Comment by YujiOshima** [comment]
Oh, please try `http://127.0.0.1:3000/katib`.
It may be a mistake on demo doc.
If you use this [manifest](https://github.com/kubeflow/katib/blob/master/manifests/modeldb/frontend/deployment.yaml), the `ROOT_PATH` was set.

**Comment by xieydd** [comment]
@YujiOshima Thanks a lot  ,  it works;
```
$ curl 127.0.0.1:3000/katib
Redirecting to <a href="/katib/">/katib/</a>
```

**Comment by xieydd** [comment]
Tensorboard is nou support yet in this demo?

```
when Redirecte to http://10.10.15.5:32300/tensorboard/random-example/i49076d26cefa4b1/ in chrome
Not Found
404
Error: Not Found
    at /modeldb/frontend/app.js:33:13
    at Layer.handle [as handle_request] (/modeldb/frontend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/modeldb/frontend/node_modules/express/lib/router/index.js:312:13)
    at /modeldb/frontend/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/modeldb/frontend/node_modules/express/lib/router/index.js:330:12)
    at next (/modeldb/frontend/node_modules/express/lib/router/index.js:271:10)
    at cookieParser (/modeldb/frontend/node_modules/cookie-parser/index.js:56:14)
    at Layer.handle [as handle_request] (/modeldb/frontend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/modeldb/frontend/node_modules/express/lib/router/index.js:312:13)
    at /modeldb/frontend/node_modules/express/lib/router/index.js:280:7
```

**Comment by xieydd** [comment]
@YujiOshima I am sorry to distrub you , but the problem is not solved yet.

**Comment by YujiOshima** [comment]
@xieydd Sorry for a late reply.
Yes, the Tensorboard is not supported yet.. sorry.
I have a plan to integrate tensorboard. I understand it is useful and important.

**Comment by xieydd** [comment]
Thanks for your reply😝
