### ISSUE TITLE
Remove MXNet example 

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/katib#2261]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Since the MXNet was made archive, the MXNet dataset was removed in the following.
So, we need to remove our MXNet example and then switch CI and examples with MXNet to another framework.

```shell
root@2a88f8620665:/opt/mxnet-mnist# python mnist.py 
2024-02-20T05:39:55Z INFO     start with arguments Namespace(num_classes=10, num_examples=60000, add_stn=False, image_shape='1, 28, 28', network='mlp', num_layers=None, gpus=None, kv_store='device', num_epochs=10, lr=0.05, lr_factor=0.1, lr_step_epochs='10', initializer='default', optimizer='sgd', mom=0.9, wd=0.0001, batch_size=64, disp_batches=100, model_prefix=None, save_period=1, monitor=0, load_epoch=None, top_k=0, loss='', test_io=0, dtype='float32', gc_type='none', gc_threshold=0.5, macrobatch_size=0, warmup_epochs=5, warmup_strategy='linear', profile_worker_suffix='', profile_server_suffix='', use_imagenet_data_augmentation=0)
2024-02-20T05:39:55Z DEBUG    Starting new HTTP connection (1): data.mxnet.io:80
2024-02-20T05:39:55Z DEBUG    http://data.mxnet.io:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 301 290
2024-02-20T05:39:55Z DEBUG    Starting new HTTP connection (1): data.mxnet.io.s3-website-us-west-1.amazonaws.com:80
2024-02-20T05:39:55Z DEBUG    http://data.mxnet.io.s3-website-us-west-1.amazonaws.com:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 403 303
download failed, retrying, 4 attempts left
2024-02-20T05:39:55Z DEBUG    Starting new HTTP connection (1): data.mxnet.io:80
2024-02-20T05:39:55Z DEBUG    http://data.mxnet.io:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 301 290
2024-02-20T05:39:55Z DEBUG    Starting new HTTP connection (1): data.mxnet.io.s3-website-us-west-1.amazonaws.com:80
2024-02-20T05:39:56Z DEBUG    http://data.mxnet.io.s3-website-us-west-1.amazonaws.com:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 403 303
download failed, retrying, 3 attempts left
2024-02-20T05:39:56Z DEBUG    Starting new HTTP connection (1): data.mxnet.io:80
2024-02-20T05:39:56Z DEBUG    http://data.mxnet.io:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 301 290
2024-02-20T05:39:56Z DEBUG    Starting new HTTP connection (1): data.mxnet.io.s3-website-us-west-1.amazonaws.com:80
2024-02-20T05:39:56Z DEBUG    http://data.mxnet.io.s3-website-us-west-1.amazonaws.com:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 403 303
download failed, retrying, 2 attempts left
2024-02-20T05:39:56Z DEBUG    Starting new HTTP connection (1): data.mxnet.io:80
2024-02-20T05:39:56Z DEBUG    http://data.mxnet.io:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 301 290
2024-02-20T05:39:56Z DEBUG    Starting new HTTP connection (1): data.mxnet.io.s3-website-us-west-1.amazonaws.com:80
2024-02-20T05:39:56Z DEBUG    http://data.mxnet.io.s3-website-us-west-1.amazonaws.com:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 403 303
download failed, retrying, 1 attempt left
2024-02-20T05:39:56Z DEBUG    Starting new HTTP connection (1): data.mxnet.io:80
2024-02-20T05:39:56Z DEBUG    http://data.mxnet.io:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 301 290
2024-02-20T05:39:56Z DEBUG    Starting new HTTP connection (1): data.mxnet.io.s3-website-us-west-1.amazonaws.com:80
2024-02-20T05:39:57Z DEBUG    http://data.mxnet.io.s3-website-us-west-1.amazonaws.com:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 403 303
Traceback (most recent call last):
  File "/opt/mxnet-mnist/mnist.py", line 86, in <module>
    fit.fit(args, sym, get_mnist_iter)
  File "/opt/mxnet-mnist/common/fit.py", line 185, in fit
    (train, val) = data_loader(args, kv)
  File "/opt/mxnet-mnist/mnist.py", line 44, in get_mnist_iter
    mnist = mx.test_utils.get_mnist()
  File "/usr/local/lib/python3.10/site-packages/mxnet/test_utils.py", line 1906, in get_mnist
    (train_lbl, train_img) = read_data(
  File "/usr/local/lib/python3.10/site-packages/mxnet/test_utils.py", line 1894, in read_data
    with gzip.open(mx.test_utils.download(label_url)) as flbl:
  File "/usr/local/lib/python3.10/site-packages/mxnet/test_utils.py", line 1812, in download
    raise e
  File "/usr/local/lib/python3.10/site-packages/mxnet/test_utils.py", line 1803, in download
    assert r.status_code == 200, "failed to open %s" % url
AssertionError: failed to open http://data.mxnet.io/data/mnist/train-labels-idx1-ubyte.gz
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Related to:
- #2259

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by tenzen-y** [comment]
As this is blocking all Katib PR merges, we should work on this ASAP.
@andreyvelich @johnugeorge WDYT?

**Comment by andreyvelich** [comment]
Yes, we should remove MXNet example from Katib Trials.
Maybe we could update this [Katib FashionMNIST example](https://github.com/kubeflow/katib/blob/master/examples/v1beta1/trial-images/pytorch-mnist/mnist.py) with the same PyTorch example as here: https://github.com/kubeflow/training-operator/blob/master/examples/sdk/create-pytorchjob-from-func.ipynb
But we need to see how fast this training will be executed on Katib E2Es with amount of resources that we have with GitHub actions.

**Comment by tenzen-y** [comment]
> Yes, we should remove MXNet example from Katib Trials. Maybe we could update this [Katib PyTorch FashionMNIST example](https://github.com/kubeflow/katib/blob/master/examples/v1beta1/trial-images/pytorch-mnist/mnist.py) with the same PyTorch example as here: https://github.com/kubeflow/training-operator/blob/master/examples/sdk/create-pytorchjob-from-func.ipynb But we need to see how fast this training will be executed on Katib E2Es with amount of resources that we have with GitHub actions.

@andreyvelich Why do we need to update this with the training-operator one? Could we just use https://github.com/kubeflow/katib/tree/master/examples/v1beta1/trial-images/pytorch-mnist?

**Comment by andreyvelich** [comment]
@tenzen-y Do we want to remove training evaluation to increase training time ?
Also, maybe we should update the PyTorch version to improve performance ?
https://github.com/kubeflow/katib/blob/master/examples/v1beta1/trial-images/pytorch-mnist/requirements.txt#L2

**Comment by tenzen-y** [comment]
> Do we want to remove training evaluation to increase training time ?

@andreyvelich I'm ok with either way. I'm just wondering if we should re-use the existing example.

> Also, maybe we should update the PyTorch version to improve performance ?
https://github.com/kubeflow/katib/blob/master/examples/v1beta1/trial-images/pytorch-mnist/requirements.txt#L2

I agree with updating PyTorch version, but I think that we can work on version updates in a separate issue.

**Comment by andreyvelich** [comment]
Sure, let's see how much time it takes for E2Es if we just re-use this example rather than MXNet training.

**Comment by tenzen-y** [comment]
> Sure, let's see how much time it takes for E2Es if we just re-use this example rather than MXNet training.

It makes sense.

**Comment by katyprogrammer** [comment]
there's still fair bit of templates yaml using this mxnet-mnist

**Comment by andreyvelich** [comment]
> there's still fair bit of templates yaml using this mxnet-mnist

@katyprogrammer Please can you share examples where do you see this ?
