### ISSUE TITLE
Katib v1alpha2 pytorchjob-example.yaml is failing

### ISSUE THREAD

**Issue by asispatra** [kubeflow/katib#702]
Katib v1alpha2 pytorchjob-example.yaml is failing.

Please find the log as below:
```
asis@paisky2:~/katib/katib/examples/v1alpha2$ kubectl create -f https://raw.githubusercontent.com/kubeflow/katib/master/examples/v1alpha2/pytorchjob-example.yaml
experiment.kubeflow.org/random-experiment created
(reverse-i-search)`exper': kubectl -n kubeflow delete ^Cperiment  pytorchjob-example
asis@paisky2:~/katib/katib/examples/v1alpha2$ kubectl get experiment -n kubeflow
NAME                STATUS    AGE
random-experiment   Running   14s
asis@paisky2:~/katib/katib/examples/v1alpha2$ kubectl get pods -n kubeflow
NAME                                                    READY   STATUS    RESTARTS   AGE
katib-controller-7f985d6cd6-6cht6                       1/1     Running   17         19h
katib-db-b48df7777-f626v                                1/1     Running   0          19h
katib-manager-7946dd5984-2pszt                          1/1     Running   8          19h
katib-manager-rest-647f694b7d-c99vc                     1/1     Running   0          19h
katib-suggestion-bayesianoptimization-94c87dd64-gwmps   1/1     Running   0          19h
katib-suggestion-grid-58d9dfb5fd-ltw9r                  1/1     Running   0          19h
katib-suggestion-hyperband-778bb768c8-5k4hv             1/1     Running   0          19h
katib-suggestion-nasrl-d84fbb8f4-szzmr                  1/1     Running   0          19h
katib-suggestion-random-7f96c4d77b-llgb5                1/1     Running   0          19h
katib-ui-6cf97db464-85ndk                               1/1     Running   0          19h
random-experiment-8xsvj587-1564470900-rwwnt             0/1     Error     0          21s
random-experiment-dv2fzqvf-1564470900-ggkdv             0/1     Error     0          21s
random-experiment-fbjlt5tq-1564470900-7mc9x             0/1     Error     0          21s
asis@paisky2:~/katib/katib/examples/v1alpha2$ kubectl -n kubeflow logs random-experiment-8xsvj587-1564470900-rwwnt
I0730 07:15:05.651777       1 main.go:61] Experiment Name: random-experiment, Trial Name: random-experiment-8xsvj587, Job Kind: PyTorchJob
F0730 07:15:08.701325       1 main.go:75] Failed to collect logs: No Pods are found in Trial random-experiment-8xsvj587
goroutine 1 [running]:
github.com/kubeflow/katib/vendor/k8s.io/klog.stacks(0xc000392500, 0xc00015e1c0, 0x78, 0xe0)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:830 +0xb1
github.com/kubeflow/katib/vendor/k8s.io/klog.(*loggingT).output(0x1e83b20, 0xc000000003, 0xc0003676c0, 0x1e0ea00, 0x7, 0x4b, 0x0)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:781 +0x25e
github.com/kubeflow/katib/vendor/k8s.io/klog.(*loggingT).printf(0x1e83b20, 0x7ffe00000003, 0x1255157, 0x1a, 0xc0002a1f18, 0x1, 0x1)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:678 +0x14e
github.com/kubeflow/katib/vendor/k8s.io/klog.Fatalf(...)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:1209
main.main()
        /go/src/github.com/kubeflow/katib/cmd/metricscollector/v1alpha2/main.go:75 +0x4e7
asis@paisky2:~/katib/katib/examples/v1alpha2$
```

- Kubeflow version: 0.6.1
- Kubernetes version: (use `kubectl version`): v1.15.1
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.2 LTS

**Comment by asispatra** [comment]
```
asis@paisky2:~/katib/katib/examples/v1alpha2$ kubectl get trials -n kubeflow
NAME                         STATUS    AGE
random-experiment-8xsvj587   Running   4m34s
random-experiment-dv2fzqvf   Running   4m34s
random-experiment-fbjlt5tq   Running   4m34s
```

**Comment by johnugeorge** [comment]
Can you share the experiment yaml?

**Comment by asispatra** [comment]
```
asis@paisky2:~/katib/katib/examples/v1alpha2$ kubectl get experiment random-experiment -n kubeflow -oyaml
apiVersion: kubeflow.org/v1alpha2
kind: Experiment
metadata:
  creationTimestamp: "2019-07-30T07:49:12Z"
  finalizers:
  - clean-data-in-db
  generation: 2
  name: random-experiment
  namespace: kubeflow
  resourceVersion: "486177"
  selfLink: /apis/kubeflow.org/v1alpha2/namespaces/kubeflow/experiments/random-experiment
  uid: e4f28ce9-3a38-48c1-8a81-25df246997fe
spec:
  algorithm:
    algorithmName: random
    algorithmSettings: null
  maxFailedTrialCount: 3
  maxTrialCount: 12
  objective:
    goal: 0.99
    objectiveMetricName: accuracy
    type: maximize
  parallelTrialCount: 3
  parameters:
  - feasibleSpace:
      max: "0.05"
      min: "0.01"
    name: --lr
    parameterType: double
  - feasibleSpace:
      max: "0.9"
      min: "0.5"
    name: --momentum
    parameterType: double
  trialTemplate:
    goTemplate:
      rawTemplate: |-
        apiVersion: "kubeflow.org/v1"
        kind: PyTorchJob
        metadata:
          name: {{.Trial}}
          namespace: {{.NameSpace}}
        spec:
         pytorchReplicaSpecs:
          Master:
            replicas: 1
            restartPolicy: OnFailure
            template:
              spec:
                containers:
                  - name: pytorch
                    image: gcr.io/kubeflow-ci/pytorch-dist-mnist-test:v1.0
                    imagePullPolicy: Always
                    command:
                      - "python"
                      - "/var/mnist.py"
                      {{- with .HyperParameters}}
                      {{- range .}}
                      - "{{.Name}}={{.Value}}"
                      {{- end}}
                      {{- end}}
          Worker:
            replicas: 2
            restartPolicy: OnFailure
            template:
              spec:
                containers:
                  - name: pytorch
                    image: gcr.io/kubeflow-ci/pytorch-dist-mnist-test:v1.0
                    imagePullPolicy: Always
                    command:
                      - "python"
                      - "/var/mnist.py"
                      {{- with .HyperParameters}}
                      {{- range .}}
                      - "{{.Name}}={{.Value}}"
                      {{- end}}
                      {{- end}}
    retain: true
status:
  conditions:
  - lastTransitionTime: "2019-07-30T07:49:12Z"
    lastUpdateTime: "2019-07-30T07:49:12Z"
    message: Experiment is created
    reason: ExperimentCreated
    status: "True"
    type: Created
  - lastTransitionTime: "2019-07-30T07:49:12Z"
    lastUpdateTime: "2019-07-30T07:49:12Z"
    message: Experiment is running
    reason: ExperimentRunning
    status: "True"
    type: Running
  currentOptimalTrial:
    observation:
      metrics: null
    parameterAssignments: null
  startTime: "2019-07-30T07:49:12Z"
  trials: 3
  trialsRunning: 3
asis@paisky2:~/katib/katib/examples/v1alpha2$
```

**Comment by johnugeorge** [comment]
Do you have pytorch-operator pod running?

**Comment by asispatra** [comment]
@johnugeorge , Looks like not running. What shall I do to make it running?
Does not it comes with Katib? Do I need to install it separately?

```
asis@paisky2:~/yaml$ kubectl get pods -n kubeflow
NAME                                                    READY   STATUS    RESTARTS   AGE
hyperband-example-nmd99cgz-z5ps4                        1/1     Running   0          128m
katib-controller-7f985d6cd6-6cht6                       1/1     Running   17         25h
katib-db-b48df7777-f626v                                1/1     Running   0          25h
katib-manager-7946dd5984-2pszt                          1/1     Running   8          25h
katib-manager-rest-647f694b7d-c99vc                     1/1     Running   0          25h
katib-suggestion-bayesianoptimization-94c87dd64-gwmps   1/1     Running   0          25h
katib-suggestion-grid-58d9dfb5fd-ltw9r                  1/1     Running   0          25h
katib-suggestion-hyperband-778bb768c8-5k4hv             1/1     Running   0          25h
katib-suggestion-nasrl-d84fbb8f4-szzmr                  1/1     Running   0          25h
katib-suggestion-random-7f96c4d77b-llgb5                1/1     Running   0          25h
katib-ui-6cf97db464-85ndk                               1/1     Running   0          25h
```
Thanks.

**Comment by asispatra** [comment]
@johnugeorge , Shall I run this to get pytorch-operator? OR there is some other steps to get this?

```
export KF_ENV=default
ks env set ${KF_ENV} --namespace=kubeflow
ks registry add kubeflow github.com/kubeflow/kubeflow/tree/master/kubeflow

ks pkg install kubeflow/pytorch-job
ks generate pytorch-operator pytorch-operator
ks apply ${KF_ENV} -c pytorch-operator
```
Thanks.

**Comment by johnugeorge** [comment]
how did you install katib? through kfctl?

**Comment by asispatra** [comment]
@johnugeorge , I have install katib using the [deploy.sh](https://github.com/kubeflow/katib/blob/master/scripts/v1alpha2/deploy.sh) script.

Thanks.

**Comment by johnugeorge** [comment]
you could install pytorch crd and operators from https://github.com/kubeflow/manifests/tree/master/pytorch-job using customize

**Comment by gaocegege** [comment]
/close

It is stale. But feel free to ask here.
